### PR TITLE
Travis setup and C99-violation fixes

### PR DESCRIPTION
**Pull request by mkfifo**
Adding a travis config with a linux target (ghc 8.0.1, cabal-install-1.24, llvm-3.5)

Travis also picked up a C99 violation, so I poked around Primitives.c and fixed a few more.

If you want to integrate Travis then I will need someone with 'member' access to DDCSF/ddc to perform some travis permission steps.
Travis integration would mean that every push to any branch is run through travis, which builds and tests under Linux (later on I can add OSX).
Travis integration would also mean every pull request is also tested, with the results posted to it, so you can see the testing results before you merge it.

To setup travis you need to:
Follow the first 2 steps here https://docs.travis-ci.com/user/getting-started/
Merge this commit

If this is accepted I can add a badge to your README showing the current travis status.

I'm currently only building for one target, I can pretty easily extend this to cover more targets including:

 - ubuntu 12.04 and 14.04
 - osx all the things
 - any version of ghc you probably care about
 - all the supported llvm versions
 - different gcc / clang versions
 - etc.

### CODE REVIEW

**Comment by mkfifo** [comment]
Please note though that the travis run currently takes ~ 29 minutes,
because I am using sudo to install things we have to use the slow infrastructure.

I think I should be able to change all of that to being local to $HOME and then use the faster infrastructure, I'm leaving that for a follow-up change though.

**Comment by mkfifo** [comment]
Here is the last travis build which includes this and the `ddc build gcc pedanticness` changes
https://travis-ci.org/mkfifo/ddc/builds/224811353

and here is a travis build of just the changes from this PR
https://travis-ci.org/mkfifo/ddc/builds/224815721

**Comment by kvanberendonck** [comment]
Just making a note that there is (or was in 2014) already a ddc build server, not sure if @benl23x5 ever got it running again after git migration.

**Comment by mkfifo** [comment]
@kvanberendonck thanks for mentioning that :)
Thankfully I spoke with @benl23x5 before I started this work.

**Pull request merged**
